name: Supabase Keep-Alive

on:
  schedule:
    # Runs every 5 days
    - cron: '0 0 */5 * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        uses: supabase/supabase-js@v2
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          curl -X GET "$SUPABASE_URL/rest/v1/rpc/keepalive" \
          -H "apikey: $SUPABASE_KEY" \
          -H "Authorization: Bearer $SUPABASE_KEY"
